# &laquo;Машинное обучение&raquo;, AI Masters


**Автор курса**: Александр Геннадьевич Дьяконов

**Семинаристы**: Илья Карчмит, Александр Краснов, Арсений Зинкевич

---

### Семинар 1: Библиотеки для анализа данных. NumPy, SciPy.

## Что будет в курсе?

### Виды активностей

* Лекции
    * Важный теоретический блок, не пропускайте!
* Семинары
    * Практические примеры того, как использовать ваши знания.
    * _Иногда_: разборы домашних работ и рассказы про лучшие решения в соревнованиях (см. ниже)
* Домашние задания
    * Формат: практическое задание или соревнование (a.k.a. контест)
    * Практические задания - решение задачек
    * Соревнования - создание ML-модели и ее тестирование на _скрытых_ данных.

### Правила курса (кратко)

#### Оценки

* За курс вы будете получать баллы по балльно-рейтинговой системе, разбалловку по которой мы пришлем вам немножко позднее.
* Ориентировочно, "зачет" по курсу можно получить, набрав ~60% от итогового балла, а оценку 10, набрав 90%+
* Оценки будут ставиться после проверки домашних заданий. Оценки за лекции и семинары не ставятся, но так вы можете получить "бонусные" баллы - об этом будет сказано отдельно.

#### Домашние задания

* В Google Classroom вы должны называться вашими именем и фамилией, чтобы вас можно было однозначно идентифицировать. Если вы так не называетесь, поменяйте это в настройках вашего аккаунта Google.
* Сдавайте только то, что нужно в задании. В большинстве д/з вам будет дан Jupyter Notebook с пропущенными ячейками, в таком случае, сдавайте только заполненный вами файл `.ipynb`.
* **Не сдавайте архивы, пожалуйста** (только если в задании не сказано это напрямую). В частности, не нужно сдавать доп. файлы с вашими функциями, прикреплять данные, которые были прикреплены в д/з и т.п.

**Дедлайны**

* Дедлайны жесткие, при сдаче после дедлайна (без уважительных причин) работа будет оценена в 0 баллов.
    * Об уважительных причинах нужно **заранее** сообщать семинаристу, который проверяет задание. Сообщайте о них хотя бы за 2 дня! (до 23:59 в субботу при дедлайне в понедельник)
* Дедлайн: обычно ставится в пн в 21:00. Рассчитываем, что вы ответственно сделаете все на выходных, а в пн спокойно **дооформите** работу и сдадите.
* Если вы не успеваете коллективно, можно попробовать устроить бунд (так же **заранее**!). Для этого пишите сообщения в чат и собирайте реакции. Если будет достаточно желающих подвинуть дедлайн - мы сможем это сделать, только не в конце семестра.
* Если вы просрочили дедлайн на 5 минут - не беда. Если просрочили на 3 часа - уже беда, за такое будем ставить нули. Обобщайте на свой страх и риск...

**Обратная связь**

* Индивидуальный фидбек по работе дается по вдохновению проверяющего. В свою очередь, это сильно мотивируется качеством вашей работы - за хорошую работу будет более качественный разбор проблем.
* После проверки всех домашек мы обычно делимся частыми ошибками в общем чате.
* Если вам все равно интересно узнать, за что вам недоначислили баллы, обращайтесь в личку к проверяющему.

**Формат связи**

* По всем вопросам можно писать в личные сообщения семинаристам (Илья, Саша, Арсений), но...
* Большинство вопросов касаются домашек! Поэтому те вопросы, ответы на которые могут быть интересны остальным, обязательно задавайте в чат, насколько бы "тупыми" они вам не казались и насколько бы сильно вы не стеснялись.

**Правила выполнения домашек**

* Иерархия инструкций
    1. Инструкция в Jupyter Notebook с домашкой
    2. Инструкция в Google Classroom / чате / Kaggle

**О проверке**

* Запуск кода и обучение моделей могут быть долгими. По этой причине мы не запускаем ваш код, а смотрим то, что видно из коробки при открытии приложенного ноутбука в Google Colab. Если какой-то вывод не виден -- его для нас нет.
* Периодически вы будете встречаться с Plotly-графиками (в частности, их использует библиотека Optuna). Такие графики по умолчанию **не видны** в Google Colab. Чтобы их было видно, нужно сохранить их себе на диск (в нужном масштабе) и вывести в нужное место вот таким образом:

```python
from IPython.display import Image
Image('plotly_image.png')
```


#### Оформление работ

В каждой домашке (кроме первой) можно будет получить дополнительные баллы за оформление работы. Нормальные работы будут получать +0, **можно получить от -5 до +5 за "особые старания"**: если вы воюете в правильную сторону - бонус, а если не туда, то штраф.

**Хорошие работы**

* Дают возможность получить до +5 баллов за оформление
* Повышают шанс более вдумчивой проверки преподавателем
* Повышают шанс получения продуктивного фидбека

**Плохие работы**

* Дают риск получить до -5 баллов штрафа за оформление
* Повышают шансы на стохастическую проверку не в вашу пользу
* Вряд ли дадут мотивацию проверяющему на продуктивный разбор ваших ошибок - старания не должны быть односторонними!

**Хорошая работа - это:**

* _Хорошая работа_
* Вынос повторяющегося кода в отдельные функции в том же ноутбуке/отдельных .py-файлах
* Старательное избегание всего повторяющегося, если это возможно и целесообразно
* Написанный код говорит сам за себя. Стороннему человеку понятно, что происходит. Если непонятно, то есть минимальные комментарии к написанному.
* Сдается на проверку ровно то, что спрашивается в задании - ни больше, ни меньше (здравый минимализм)
* Экономятся ячейки Jupyter Notebook (не нужно писать по строчке в ячейке; думайте о ячейке как о смысловом блоке кода)
* Результатом работы ячейки (помимо всего прочего) является вывод какой-то вспомогательной информации/визуализации (например, на тему того, что происходит в ячейке)
* Графики имеют адекватный размер, размер шрифтов, необходимые подписи, понятен смысл графика и обозначения на нем и т.п.

**Плохая работа - это:**

* _Плохая работа_
* `print(мусор, дебаг-инфа, ...)` - все, что не нужно проверяющим
* Сдача ноутбуков с не выполненными из-за исключений ячейками
* Повторяющийся код
* Непонятные и незакомментированные куски кода
* Расход ячеек впустую (например, по строчке в ячейке без внятной причины)
* Плохие графики: непонятный смысл графика, несообразный размер (мелкий/огромный график), неясные размеры шрифтов, отсутствие легенды на графиках, где она нужна и т.п.

**TL;DR:**<br/>
Хорошая работа - это про адекватность и компактность, а не про то, чтобы вставлять в текст emoji, писать огромные прелюдии к каждому блоку д/з и т.п.



## Сегодня будет:

Знакомство с некоторыми библиотеками, которые широко используются в анализе данных.

В частности, в ноутбуке рассматриваются следующие темы:

* Проблемы стандартных питоновских структур данных при матричных операциях;
* Базовые операции при работе с многомерными массивами в библиотеке NumPy;
* Сложная индексация массивов и broadcasting.

![numpy-operations.png](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/numpy-operations.png)

## Массивы в Python

In [ ]:
a = [7, 2, 9, 10]

In [ ]:
a[0]

7

In [ ]:
a[0:3]

[7, 2, 9]

In [ ]:
a = [0, 1.1, 'ground control...']

In [ ]:
b = [30, 1e-6, 'check...']

Не совсем массив :(

![list-array.png](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/list-array_list_only.png)

In [ ]:
[i + j for i, j in zip(a, b)]

[30, 1.100001, 'ground control...check...']

## Многомерные массивы в Python

Здесь и далее будем считать, что понятия "многомерные массивы" и "матрицы" эквивалентны.

Многомерные массивы в Python можно рассмаривать, например, как списки списков:

In [ ]:
a = [[ 0,  1,  2,  3,  4],
     [ 5,  6,  7,  8,  9],
     [10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]]
a

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

In [ ]:
a[0][2]

2

Одна из проблем списков — отсутствие поэлементных и матричных операций.

<font color='red'>**Задача 1.**</font> Напишите функцию `get_column(a, i)`, которая получает столбец матрицы `a` с индексом `i`. <font color='red'>**Не используйте библиотеку NumPy**!</font>

In [ ]:
# your code here

def get_column(a, i):
    return [row_j[i] for row_j in a]

In [ ]:
assert get_column(a, 0) == [0, 5, 10, 15]
assert get_column(a, 2) == [2, 7, 12, 17]
assert get_column(a, -1) == [4, 9, 14, 19]

b = [[ 1,  3],
     [ 6,  8],
     [11, 13],
     [16, 18]]

assert get_column(a, slice(1, None, 2)) == b

<font color='red'>**Задача 2.**</font> Напишите функцию `transpose(a)`, которая получает транспонирует матрицу `a`. <font color='red'>**Не используйте библиотеку NumPy**!</font>

In [ ]:
# your code here

def transpose(a):
    return list([get_column(a, i) for i in range(len(a[0]))])


In [ ]:
b = [[0, 5, 10, 15],
     [1, 6, 11, 16],
     [2, 7, 12, 17],
     [3, 8, 13, 18],
     [4, 9, 14, 19]]

assert transpose(a) == b

Создадим матрицу `A` размером $500 \times 10$, в которой ij-ый элемент будет равен 10 * i + j.

In [ ]:
A = [[10 * i + j for j in range(10)] for i in range(500)]

A[:5]

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]

Умножим матрицу `A` поэлементно на 2.

In [ ]:
%%timeit

# Вариант 1: через метод list.append

A_new = []

for x_row in A:
    x_row_new = []
    for xy_elem in x_row:
        x_row_new.append(2 * xy_elem)
    A_new.append(x_row_new)

A_new

301 µs ± 8.16 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%%timeit

# Вариант 2: через через генераторы списоков (list comprehension)

A_new = [[2 * e for e in row] for row in A]
A_new

450 µs ± 119 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Попробуем сделать то же самое, но с использованием бибилиотеки `numpy`.

In [ ]:
# НИКОГДА НЕ ДЕЛАЙТЕ ТАК
# from numpy import *

# ВСЕГДА ДЕЛАЙТЕ ТАК
import numpy as np

In [ ]:
# выделяем память под матрицу (malloc + memset)
A_new = np.zeros((500, 10))

In [ ]:
%%timeit
for row_i in range(500):
    for col_i in range(10):
        A_new[row_i][col_i] = col_i + 10 * row_i


2.44 ms ± 585 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Все операции с `numpy.ndarray` по-умолчанию поэлементные. Таким образом, умножение на два это всего лишь:

In [ ]:
A_numpy = np.asarray(A, dtype=int)
A_numpy[:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
A_new = 2 * A_numpy
A_new[:5]

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

Оценим скорость работы.

In [ ]:
%%timeit

A_new = 2 * A_numpy

6.3 µs ± 1.71 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Таким образом, главным преимуществом библиотеки NumPy являтся высокая скорость работы: ускорение почти в 100 раз по сравнению с лучшим вариантом на Python.

| Реализация       | Время работы |
|------------------|--------------|
| lists            | 511 µs       |
| lists generators | 340 µs       |
| python + numpy   | ???          |
| numpy            | 3.15 µs      |

## Библиотека NumPy

### Создание массивов

**Вариант 1**: создание `numpy.ndarray` заданных форм и характеристик:
* `np.zeros` – матрица из нулей;
* `np.ones` – матрица из единицы;
* `np.eye` – единичная марица;
* `np.arange`, `np.linspace` – массивы с дискретным шагом.

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5, ))

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 8, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

**Вариант 2**: создание из Python-объектов

In [ ]:
a = [[ 0,  1,  2,  3,  4],
     [ 5,  6,  7,  8,  9],
     [10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]]

a = np.asarray(a, dtype=int)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.asarray(a, dtype=np.uint8)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]], dtype=uint8)

### Поэлементные операции со скалярами

`numpy.ndarray` поддерживает арифметические поэлементые операции:

`c = op(a, sc)` $\Longleftrightarrow$ `c[i,j] = op(a[i,j], sc)`

In [ ]:
a + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
a * 10

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [ ]:
a / 10

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

In [ ]:
a // 10

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Есть и поддержка более сложных математических функций.

In [ ]:
a ** 2  # same as np.pow(a, 2)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [ ]:
np.sqrt(a ** 2)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [ ]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721]])

И поддержка логических операций.

In [ ]:
a >= 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### Устройство массивов, их размерность и размеры

![numpy_array_abstraction.png](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/numpy_array_abstraction.png)

In [ ]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 0]],
             dtype=float)
a

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

Массивы `numpy.ndarray` в основе себя используют обычные массивы фиксированного размера (атрибут `data`).

Многомерные массивы хранятся как один большой последовательный блок памяти.

In [ ]:
a.data

У `numpy.ndarray` есть атрибут `dtype`, который содержит информацию о типе данных, хранимых в массиве.

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.dtype.itemsize  # sizeof(float64)

8

| Тип данных | Описание |
|:---------- |:-------- |
| bool       | Boolean (True or False) stored as a byte |
| int        | Platform integer (normally either int32 or int64) |
| int8       | Byte (-128 to 127) |
| int16      | Integer (-32768 to 32767) |
| int32      | Integer (-2147483648 to 2147483647) |
| int64      | Integer (-9223372036854775808 to 9223372036854775807) |
| uint8      | Unsigned integer (0 to 255) |
| uint16     | Unsigned integer (0 to 65535) |
| uint32     | Unsigned integer (0 to 4294967295) |
| uint64     | Unsigned integer (0 to 18446744073709551615) |
| float      | Shorthand for float64 |
| float32    | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa |
| float64    | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa |
| complex    | Shorthand for complex128 |
| complex64  | Complex number, represented by two 32-bit floats (real and imaginary components) |
| complex128 | Complex number, represented by two 64-bit floats (real and imaginary components) |

Поменять тип массива можно с помощью метода `astype`, что очевидно приведет копированию данных.

In [ ]:
a.astype(int).dtype

dtype('int64')

In [ ]:
a.astype(np.int8).dtype

dtype('int8')

У `numpy.ndarray` есть атрибут `shape` – размер массива.

In [ ]:
a.shape

(4, 5)

In [ ]:
a.strides

(40, 8)

Для изменения размера массива используется метод `reshape`. Метод возвращает новый объект, который имеет тот же атрибут `data`, что и исходный массив. Т.е. копирования данных обычно **НЕ происходит**.

In [ ]:
a.reshape(5, 2)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [ ]:
# размеры должны быть корректными

a.reshape(5, 3)

ValueError: cannot reshape array of size 10 into shape (5,3)

In [ ]:
# -1 говорит о том, что длина размерности может быть вычислена автоматически

a.reshape(-1, 2)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [ ]:
a.ravel()  # same as a.reshape(-1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9., 0.])

Еще раз подчеркнем, что копирования данных обычно **не происходит**!

In [ ]:
a

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [ ]:
b = a.reshape(-1, 2)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [ ]:
a[-1, -1] = 10
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
b

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

Фиктивная размерность – размерность длины 1. Фиктивная размерность нужна для того, чтобы совершать матричные операции, например, умножение вектора на матрицу.

In [ ]:
a_c = a.copy()
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
a_c[0] = -10
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
a = a.ravel()
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
a.shape

(10,)

In [ ]:
b = a[np.newaxis, :]  # same as a.reshape(1, -1)
b

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
b.shape

(1, 10)

In [ ]:
b = a[:, np.newaxis]  # same as a.reshape(-1, 1)
b

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [ ]:
b.shape

(10, 1)

In [ ]:
np.newaxis is None

True

In [ ]:
a[:, None]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

### 🧐 Интересный факт про размерность массивов и копирование

У `numpy.ndarray` есть атрибут `strides`, который регулирует порядок обхода массива (атрибут `data`). Этот атрибут очень важен для многомерных массивов.

Первое число показывает, сколько байт нужно прочитать, чтобы переместиться на следующую строку и остаться в том же столбце.

Второе число показывает, сколько байт нужно прочитать, чтобы переместиться на следующий столбец и остаться в той же строке.

In [ ]:
c = np.arange(12).reshape(2, -1)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
c.shape, c.dtype.itemsize, c.strides

((2, 6), 8, (48, 8))

In [ ]:
assert c.strides == (c.shape[1] * c.dtype.itemsize, c.dtype.itemsize,)

# для перехода к следующей строке нужно считать 6 * 8 байт
# для перехода к следующему стобцу нужно прочитать 8 байт

c.strides  # (6 * 8, 8)

Поменяем размерность массива и увидим, как меняется атрибут `strides`.

In [ ]:
c = c.reshape(-1, 2)
c

In [ ]:
c.shape

In [ ]:
assert c.strides == (c.shape[1] * c.dtype.itemsize, c.dtype.itemsize,)

# для перехода к следующей строке нужно считать 2 * 8 байт
# для перехода к следующему стобцу нужно прочитать 8 байт

c.strides  # (2 * 8, 8)

Операция транспонирования, как уже говорилось выше не приводит к копированию данных. Она меняет атрибут `strides`, который регулирет порядок обхода массива.

Напомним, что `c.data = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]`.

In [ ]:
c = c.T
c

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [ ]:
c.shape

(6, 2)

In [ ]:
assert c.strides == (c.dtype.itemsize, c.shape[0] * c.dtype.itemsize, )

# для перехода к следующей строке нужно считать 8 байт
# для перехода к следующему столбцу нужно прочитать 2 * 8 байт

c.strides  # (8, 2 * 8)

(8, 48)

У массивов `numpy.ndarray` есть операция транспонирования. Она тоже _обычно_ **НЕ приводит** к копированию данных.

In [ ]:
a.T

In [ ]:
a.transpose()

Почему я выше писал, что копирование "_обычно_" не происходит? Это зависит от того, к какой матрице вы применяете `reshape` или `transpose`:

In [ ]:
c = np.arange(20).reshape(5, 4).copy()
c


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
c.T[-1, -1] = 100  # all right!
c

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18, 100]])

In [ ]:
d = c.T.reshape(10, 2)
d[-1, -1] = 200
d

array([[  0,   4],
       [  8,  12],
       [ 16,   1],
       [  5,   9],
       [ 13,  17],
       [  2,   6],
       [ 10,  14],
       [ 18,   3],
       [  7,  11],
       [ 15, 200]])

In [ ]:
c  # all... right?

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18, 100]])

Т.е. копирование иногда все же происходит, если NumPy не может выразить операцию через strides!

### Поэлементные бинарные операции

In [ ]:
a = [[1, 0, 0, 0, 1], [1, 0, 1, 0, 1]]
a = np.asarray(a)
a

array([[1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1]])

In [ ]:
b = np.arange(1, 11).reshape(-1, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Для начала рассмотрим массивы одинаковых размеров.

`numpy.ndarray` поддерживает арифметические поэлементые операции над двумя массивами:

`c = op(a, b)` $\Longleftrightarrow$ `c[i,j] = op(a[i,j], b[i,j])`

In [ ]:
a + b

array([[ 2,  2,  3,  4,  6],
       [ 7,  7,  9,  9, 11]])

In [ ]:
a * b

array([[ 1,  0,  0,  0,  5],
       [ 6,  0,  8,  0, 10]])

И некоторые более сложные функции...

In [ ]:
(b <= 5).astype(int)

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0]])

In [ ]:
np.fmax(a, (b <= 5).astype(int))   # element-wise maximum

array([[1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1]])

Есть и поддержка булевых операций.

In [ ]:
a == (b <= 5).astype(int)

array([[ True, False, False, False,  True],
       [False,  True, False,  True, False]])

Есть поддержка матричного умножения.

In [ ]:
a @ b.T  # same as np.matmul(a, b.T)

array([[ 6, 16],
       [ 9, 24]])

In [ ]:
np.dot(a, b.T)  # same as a.dot(b.T)

array([[ 6, 16],
       [ 9, 24]])

### Приведение размерностей (Broadcasting)

Пусть, нам дана матрица $X$ размером $5 \times 10$ и вектор $y$ длины 10. Пусть, мы хотим прибавить вектор к каждой строке матрицы.

In [ ]:
x = np.arange(50).reshape(-1, 10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x * y

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81],
       [  0,  11,  24,  39,  56,  75,  96, 119, 144, 171],
       [  0,  21,  44,  69,  96, 125, 156, 189, 224, 261],
       [  0,  31,  64,  99, 136, 175, 216, 259, 304, 351],
       [  0,  41,  84, 129, 176, 225, 276, 329, 384, 441]])

In [ ]:
x + y

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [30, 32, 34, 36, 38, 40, 42, 44, 46, 48],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])

Наивный способ работает верно.

Поменяем условие, пусть, $y$ – вектор длины 5. Пусть, мы хотим прибавить вектор к каждому столбцу матрицы.

In [ ]:
y = np.arange(5)
y

In [ ]:
x + y

Наивный способ не работает. Попробуем воспользоваться приведением размерностей.

In [ ]:
y[:, np.newaxis].shape

In [ ]:
x + y[:, np.newaxis]  # same as x + y.reshape(-1, 1)

![numpy_broadcasting](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/numpy_broadcasting.png)

**Правило приведения размерностей (broadcasting):**
1. Предположим, что `a.shape = (a_1, a_2, ..., a_n)` и `b.shape = (b_1, b_2, ..., b_n)`. Над `a` и `b` можно произвести поэлементую бинарную операцию, если $\forall \; i \in \overline{1..n}$ выполнено хотя бы одно из условий:
    * `a_i == b_i`;
    * `a_i == 1`;
    * `b_i == 1`.


2. Если размерности не совпадают, то к массиву меньшей размерности добавляются ведущие фиктивные размерности.

Документация: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

Проверить явное приведение размерности можно через функции `np.broadcast_to` и `np.broadcast_arrays`.

<font color='red'>**Задача 4.**</font> Какие из этих команд будут выполняться с ошибкой? <font color='lightgrey'>А где третья задача?</font>

1. `np.ones((2, 3)) + np.ones(3)`

2. `np.ones(2) + np.ones((2, 3))`

3. `np.zeros((4, 3)) + np.ones((4, 1))`

4. `np.zeros((3, 4)) + np.ones((4, 3))`

5. `np.zeros((1, 3, 5)) + np.zeros((1, 3))`

6. `np.zeros((5, 3, 1)) + np.zeros((1, 5))`

In [ ]:
np.ones((2, 3)) + np.ones(3)

array([[2., 2., 2.],
       [2., 2., 2.]])

<font color='red'>**Задача 5.**</font> Таблица умножения. Создайте массив $9 \times 9$, элементы которого являются произведениями индексов столбца и строки. Индексы нумеруются с 1.

In [ ]:
# your code here

mult_table = None

In [ ]:
np.arange(5) @ np.arange(5)

np.int64(30)

In [ ]:
np.einsum

<function einsum at 0x7def3aa01230>

In [ ]:
col = np.arange(1, 10).reshape(-1, 1)
row = np.arange(1, 10).reshape(1, -1)
col * row

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [ ]:
mult_table

In [ ]:
assert mult_table.shape == (9, 9)

for i in range(mult_table.shape[0]):
    for j in range(mult_table.shape[0]):
        assert mult_table[i, j] == (i + 1) * (j + 1)

### Операции над булевыми массивами

In [ ]:
a = np.asarray([ True,  True, False, False,  True])
b = np.asarray([ True, False, False,  True, False])
c = np.asarray([False,  False, True,  True, False])

a, b

(array([ True,  True, False, False,  True]),
 array([ True, False, False,  True, False]))

In [ ]:
np.logical_not(a)

array([False, False,  True,  True, False])

In [ ]:
~a   # same as np.bitwise_not(a)

array([False, False,  True,  True, False])

In [ ]:
np.logical_and(a, b), np.logical_or(a, b), np.logical_xor(a, b)

(array([ True, False, False, False, False]),
 array([ True,  True, False,  True,  True]),
 array([False,  True, False,  True,  True]))

In [ ]:
(
    a & b,  # same as np.bitwise_and(a, b)
    a | b,  # same as np.bitwise_or(a, b)
    a ^ b,  # same as np.bitwise_xor(a, b)
)

(array([ True, False, False, False, False]),
 array([ True,  True, False,  True,  True]),
 array([False,  True, False,  True,  True]))

In [ ]:
(a & b) | c

array([ True, False,  True,  True, False])

<font color='red'>**Не используйте**</font> стандартные Python-операторы `and`, `or`, `not` вместе с NumPy-массивами. О причине этого - позже.

То же самое относится к функциям `sum`, `any`, `all` и некоторым другим стандартным агрегирующим функциям. Кстати, о них:

### Агрегирующие операции

In [ ]:
np.random.seed(5555)

a = np.random.randint(0, 10, size=(3, 7), )
a[1, 3] = 15

a

array([[ 2,  3,  0,  5,  2,  0,  3],
       [ 8,  8,  0, 15,  1,  5,  3],
       [ 0,  1,  6,  2,  1,  4,  5]])

Для `numpy.ndarray` есть поддержка аггрегирующих операций: `min`, `max`, `argmin`, `argmax`, `sum`, `prod`, `mean`, `std`, `var` и др.

In [ ]:
a.min(), a.max(), a.sum(), a.prod(), a.mean()

(np.int64(0),
 np.int64(15),
 np.int64(74),
 np.int64(0),
 np.float64(3.5238095238095237))

In [ ]:
np.min(a), np.max(a), np.sum(a), np.prod(a), np.mean(a)

(np.int64(0),
 np.int64(15),
 np.int64(74),
 np.int64(0),
 np.float64(3.5238095238095237))

<img src="https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/numpy_axes.png" width="350px">

`a.agg(axis=axis)` – агрегирующая операция вдоль размерности (оси) `axis`:
* выполняет редукцию (агрегирующую операцию) по размерности (оси) `axis`;
* удаляет размерности (ось) `axis` из исходного массива (аргумент `keep_dims=False`).

`axis=0` – размерность строк, `axis=1` – размерность столбцов.

In [ ]:
a

array([[ 2,  3,  0,  5,  2,  0,  3],
       [ 8,  8,  0, 15,  1,  5,  3],
       [ 0,  1,  6,  2,  1,  4,  5]])

In [ ]:
a.min(axis=0)

array([0, 1, 0, 2, 1, 0, 3])

In [ ]:
a.sum(axis=1)

array([15, 40, 19])

In [ ]:
a.argmax(axis=1)

array([3, 3, 2])

Для сравнения чисел с плавающей точкой **НУЖНО** использовать `close`.

In [ ]:
np.random.seed(4987)

a = np.random.random(size=(2, 5))
b = a + np.random.random(size=(2, 5)) * 1e-5

In [ ]:
np.isclose(a, b).all()

np.False_

In [ ]:
np.isclose(a, b, atol=1e-3).all()

np.True_

**Не используйте** встроенные агрегирующие операции python.

Первая причина – это скорость.

In [ ]:
b = np.random.randint(0, 10, size=(1_000, 1_000))
b[36, 42] = 20
b = b.ravel()

In [ ]:
%%timeit

b.max()

In [ ]:
%%timeit

max(b)

Вторая причина – не совсем очевидное поведение.

In [ ]:
sum(a)  # same as a.sum(axis=0)

array([10, 12,  6, 22,  4,  9, 11])

Над булевыми массивами можно совершать агрегирующие логические операции.

In [ ]:
a = np.asarray([[True, True,  False, False, True ],
                [True, False, False, True,  False]])
a

In [ ]:
a.all(), np.all(a)

In [ ]:
a.any(), np.any(a)

In [ ]:
a.all(axis=0)

In [ ]:
a.any(axis=0)

### Индексация

Подробное описание: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

**Замечание:** индексация может быть использована не только для получения значений, но и для их присвоения.

![numpy_indexing](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/numpy_indexing.png)

In [ ]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

`numpy.ndarray` поддерживает все те же способы индексации, что и обычный список. Сначала указываются строки, затем столбцы. При индексации исключительно по строкам, индексацию по столбцам можно опустить.

In [ ]:
a[0]  # заметьте, исчезла фиктивная размерность  # same as a[0, :]

array([0, 1, 2, 3])

In [ ]:
a[:2]  # same as a[:2, :]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a[:, 0]  # и здесь тоже исчезла фиктивная размерность

array([0, 4, 8])

In [ ]:
a[:2, ::2]

array([[0, 2],
       [4, 6]])

**Сложная индексация (Fancy indexing)**

![numpy_indexing_fancy](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/numpy_indexing_fancy.png)

Булевы массивы также можно использовать для индексации. Такие массивы называются масками.

In [ ]:
np.random.seed(7964)

A = np.random.randint(0, 8, size=(5, 5))
A[2, 3] = 10
A

In [ ]:
A[A < 4]

Маски можно создавать не для всей матрицы, а только для строк или столбцов.

In [ ]:
A[A[:,0] < 3,:]

Для получения индексов, где выполнено условие (значение истино) используеттся функция `np.where`. Результат этой функции можно использовать для индексации.

Индексация по результату `np.where` является сложной индексацией (об этом ниже).

In [ ]:
A

In [ ]:
np.where(A < 4)

In [ ]:
A[np.where(A < 4)]

<font color='red'>**Задача 6.**</font> Даны матрицы $A$ размера $(n \times d)$ и $B$ размера $(m \times d)$. Напишите функцию `find_equal_lines(A, B)`, которая найдет в A все строки, содержащиеся в B. Не используйте циклы!

In [ ]:
A = np.array([
    [1, 2, 3],
    [1, 2, 1],
    [4, 5, 6],
    [1, 2, 1],
])

B = np.array([
    [4, 5, 6],
    [4, 5, 6],
    [1, 2, 3],
])

In [ ]:
# your code here

def find_equal_lines(A, B):
    return

In [ ]:
indices = find_equal_lines(A, B)

assert (indices == [0, 2]).all()

<font color='red'>**Задача 7.**</font> Дана матрица $B$ размера $(5 \times 5)$. Получите столбцы, в которых число положительных элементов больше числа отрицательных. Результат сохраните в переменную `B_masked`. Используйте индексацию с использованием булевых массивов.

In [ ]:
np.random.seed(2238)

B = np.random.randint(-5, 5, size=(5, 5))
B

In [ ]:
# your code here

B_masked = None

In [ ]:
assert (B_masked == B[:, [0, 1, -1]]).all()

В массиве `numpy.ndarray` можно выбрать значения, стоящие в нескольких (более 1) конкретных строках ИЛИ столбцах.

In [ ]:
np.random.seed(7964)

A = np.random.randint(0, 8, size=(5, 5))
A[2, 3] = 10
A

In [ ]:
A[[1, 3, 4],:]

По каждой размерности подаются массивы одинаковых размеров, элементы которых соответствуют индексам каждой размерности. Тогда, на выходе будет массив размера этих массивов, элементы которого будут соответствовать элементам исходного массива, взятых в точках, соответствующих поданным массивам.

In [ ]:
A[[0, 1, 1], [2, 1, 2]]

Если требуется взять значения, стоящие в определенных строках и столбцах, то для этого можно использовать функцию `np.ix_`.

In [ ]:
A[np.ix_([2, 4, 3], [0, -1])]

**Разница между view и копированием**

<img src='https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/view_vs_copy.png' width=500 />

При некоторых видах операций индексации, транспонирования, изменения размеров и т.п. получается view (новый объект, который ссылается на те же данные), в других – копия.

Поподробнее об этом можно прочитать тут:

https://numpy.org/doc/stable/user/basics.copies.html

In [ ]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 0]],
             dtype=float)
a

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [ ]:
b = a.view()
b

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [ ]:
b[1, 1] = 99.0
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., 99.,  8.,  9.,  0.]])

In [ ]:
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., 99.,  8.,  9.,  0.]])

In [ ]:
b = a.view(dtype=np.uint8)  # views memory as different data type
b

array([[  0,   0,   0,   0,   0,   0, 240,  63,   0,   0,   0,   0,   0,
          0,   0,  64,   0,   0,   0,   0,   0,   0,   8,  64,   0,   0,
          0,   0,   0,   0,  16,  64,   0,   0,   0,   0,   0,   0,  20,
         64],
       [  0,   0,   0,   0,   0,   0,  24,  64,   0,   0,   0,   0,   0,
        192,  88,  64,   0,   0,   0,   0,   0,   0,  32,  64,   0,   0,
          0,   0,   0,   0,  34,  64,   0,   0,   0,   0,   0,   0,   0,
          0]], dtype=uint8)

In [ ]:
b[0, -1] = 65
b

array([[  0,   0,   0,   0,   0,   0, 240,  63,   0,   0,   0,   0,   0,
          0,   0,  64,   0,   0,   0,   0,   0,   0,   8,  64,   0,   0,
          0,   0,   0,   0,  16,  64,   0,   0,   0,   0,   0,   0,  20,
         65],
       [  0,   0,   0,   0,   0,   0,  24,  64,   0,   0,   0,   0,   0,
        192,  88,  64,   0,   0,   0,   0,   0,   0,  32,  64,   0,   0,
          0,   0,   0,   0,  34,  64,   0,   0,   0,   0,   0,   0,   0,
          0]], dtype=uint8)

In [ ]:
a

array([[1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 3.2768e+05],
       [6.0000e+00, 9.9000e+01, 8.0000e+00, 9.0000e+00, 0.0000e+00]])

### Конкатенация массивов

In [ ]:
from itertools import chain, zip_longest

def print_as_columns(*args, sep='\t'):
    """
    print arrays as columns
    """
    args = list(map(lambda s: s.split('\n'), args))
    width = max(map(len, chain.from_iterable(args)))

    fill = lambda s: '{:<{width}s}'.format(s, width=width)
    fillvalue = fill('')

    args = map(lambda e: map(fill, e), args)
    args = map(sep.join, zip_longest(*args, fillvalue=fillvalue))
    print(*args, sep='\n')

In [ ]:
np.random.seed(1398)

c = np.random.permutation(np.arange(0, 12))
i = c.shape[0] // 2

a, b = c[:i], c[i:]
a, b = a.reshape(3, 2), b.reshape(3, 2)

Конкатенация массивов по вертикали.

In [ ]:
print_as_columns(repr(a), repr(b))
np.vstack((a, b))   # same as np.concatenate((a, b), axis=0)

Конкатенация массивов по горизонтали.

In [ ]:
print_as_columns(repr(a), repr(b))
np.hstack((a, b))   # same as np.concatenate((a, b), axis=0)

### Сортировка

In [ ]:
np.random.seed(5555)

a = np.random.randint(10, 20, size=(3, 7))
a[1, 3] = 99

a

In [ ]:
b = a.copy()
b.sort(axis=1)  # inplace
b

In [ ]:
np.sort(a, axis=1)   # new object

И конечно же есть операция `argsort`.

In [ ]:
a.argsort(axis=1)  # same as np.argsort(a, axis=1)

In [ ]:
c = a.ravel() * 5

In [ ]:
np.argpartition(c, 10)

<font color='red'> Как работает `argpartition`?</font>

### Получение уникальных элементов

In [ ]:
np.unique(a)

In [ ]:
np.unique(a, return_counts=True)

In [ ]:
np.bincount(a)

In [ ]:
np.bincount(a.ravel())

### Линейная алгебра

https://numpy.org/doc/stable/reference/routines.linalg.html

In [ ]:
# нормы векторов
np.linalg.norm(A, axis=1, ord=1) # np.abs + np.sum

In [ ]:
# нормы векторов
np.linalg.norm(A, axis=1, ord=2) # np.power / **2 + np.sum

## Библиотека SciPy

SсiPy — библиотека для сложных научных вычислений в Python, интегрированная с numpy.
В частности, SciPy включает в себя:

* операции линейной алгебры (scipy.linalg);
* реализации методов оптимизации (scipy.optimize);
* статистические критерии и сложные распределения (scipy.stats);
* функции для численного интегрирования (scipy.integrate).

**Важно:** некоторые из операций есть как в numpy, так и в scipy.

**Важно:** scipy — более тяжеловесен чем numpy, т.к. использует внутри себя процедуры языка Fortran.

Более подробный обзор библиотеки можно получить здесь:

http://scipy-lectures.org/intro/scipy.html

### Поиск расстояний между векторами

In [ ]:
from scipy.spatial.distance import cdist

In [ ]:
np.random.seed(63)

a = np.random.choice(10, size=10, replace=False).reshape(-1, 2)
b = np.random.choice(10, size=10, replace=False).reshape(-1, 2)

In [ ]:
print_as_columns(repr(a), repr(b))

In [ ]:
cdist(a, b)

In [ ]:
cdist(a, b, metric='cityblock')

### SVD разложение

In [ ]:
from scipy.linalg import svd  # eще есть np.linalg.svd

In [ ]:
A = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [ ]:
U, s, Vh = svd(A, full_matrices=True)

In [ ]:
np.allclose(A, U @ np.diag(s) @ Vh)

### Интерполяция

In [ ]:
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
from scipy.optimize import curve_fit

In [ ]:
np.random.seed(56)

x_data = np.linspace(-5, 5, num=50)
y_data = 2.9 * np.sin(1.5 * x_data) + np.random.normal(size=50)

In [ ]:
plt.plot(x_data, y_data, 'o')

In [ ]:
def fitting_function(x, a, b):
    return a * np.sin(b * x)

In [ ]:
params, params_covariance = curve_fit(fitting_function, x_data, y_data)

In [ ]:
params

In [ ]:
curve_y_data = [fitting_function(x, *params) for x in x_data]

In [ ]:
plt.plot(x_data, y_data, 'o')
plt.plot(x_data, curve_y_data)

### Minimize

In [ ]:
from scipy.optimize import minimize, minimize_scalar

In [ ]:
# Можем минимизровать
def f(x):
    return 3 * x ** 4 - 2 * x + 1

res = minimize_scalar(f)

plt.plot(np.arange(-2, 2, 0.05), f(np.arange(-2, 2, 0.05)))
plt.scatter(res.x, res.fun, marker="*", s = 100, c = 'r')

print(res)

In [ ]:
# Можем минимизровать с границами

res = minimize_scalar(f, method='bounded', bounds=(-1.5, -1))

fig, ax = plt.subplots()
plt.plot(np.arange(-2, 2, 0.05), f(np.arange(-2, 2, 0.05)))
ax.axvspan(-1.5, -1, 0, 50, alpha=0.5, color='red')
plt.scatter(res.x, res.fun, marker="*", s = 100, c = 'r')

print(res)

In [ ]:
# Можем минимизирвовать функции от многих переменных

def g(arguments):
    x, y, z = arguments[0], arguments[1], arguments[2]
    return 3 * x ** 4 * y * z ** 2 - z * x + x

res = minimize(g, [1, 3, 0])
res

### Оптимизация с условиями

https://habr.com/ru/company/ods/blog/448054/

### Разреженные матрицы

https://docs.scipy.org/doc/scipy/reference/sparse.html

https://matteding.github.io/2019/04/25/sparse-matrices/

### Must-reads из документации NumPy

0. Indexing in NumPy: https://numpy.org/doc/stable/user/basics.indexing.html
1. Broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html


## Что почитать еще?

1. Jake VanderPlas. Python Data Science Handbook. (Вандер Плас Дж. Python для сложных задач.)
[англ.](https://jakevdp.github.io/PythonDataScienceHandbook/)
2. Wes McKinney. Python for Data Analysis (Маккини Уэс. Python и анализ данных)